spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:online-store;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
     ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true